{grid:'GYBRRGGYBGYBRYBRYBGYBRYBRYRGYBGYBRYRRYBGYBRBRRRBGYYRBRRRBGYYBBR',target:2,budget:5,tap:[1, 3],seq:'RGYRB'},
{grid:'GGGRRYYGYYBBBRRYGYYBYBYYGGYYYYBYRRRYGBGGYYRRBGBBGBBBBBGBBGYYYYY',target:2,budget:5,tap:[2, 2],seq:'YGRYB'},
{grid:'RRRGGRRRRRRRGGRRRRYBYBYBYBYBYBYBYBYBRRRGGRRRRBBBGBBBBBRRRGGRRRR',target:2,budget:5,tap:[3, 5],seq:'BGRYB'}